### ISSUE TITLE
Microsoft IE browser in my script given below not running giving error message.

### ISSUE THREAD

**Issue by rfmirza123** [rfmirza786/vault#1]
I am trying to run Microsoft IE browser in my script given below.  I have downloaded 64bit IE driver and provided the path. 
I am also attaching the error message received on Eclipse console. 

package NaveenPackage_New;

		import java.util.concurrent.TimeUnit;
		import org.openqa.selenium.By;
		import org.openqa.selenium.WebDriver;
		import org.openqa.selenium.chrome.ChromeDriver;
		import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.ie.InternetExplorerDriver;

		public class InternetExplorerWebDriverBasic {	
			
			public static WebDriver driver;		//Chrome Browser needs this line
			
			public static void main(String[] args) throws InterruptedException {System.setProperty("webdriver.ie.driver","C:\\Users\\rfmir\\OneDrive\\Desktop\\selenium12\\IEDriverServer.exe");
				WebDriver driver = new InternetExplorerDriver();
				
				Thread.sleep(3000);
driver.manage().window().maximize();
				driver.manage().deleteAllCookies();
				driver.get("http://www.google.com");
				Thread.sleep(2000);
	}
		}
---------------------------------------------------------------------------------------------------
Started InternetExplorerDriver server (64-bit)
2.45.0.0
Listening on port 47585
Exception in thread "main" org.openqa.selenium.NoSuchSessionException: Unexpected error launching Internet Explorer. Protected Mode settings are not the same for all zones. Enable Protected Mode must be set to the same value (enabled or disabled) for all zones. (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 116 milliseconds
Build info: version: '3.14.0', revision: 'aacccce0', time: '2018-08-02T20:05:20.749Z'
System info: host: 'DESKTOP-18F4G47', ip: '192.168.0.6', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_171'
Driver info: driver.version: InternetExplorerDriver
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:214)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:166)
	at org.openqa.selenium.remote.JsonWireProtocolResponse.lambda$new$0(JsonWireProtocolResponse.java:53)
	at org.openqa.selenium.remote.JsonWireProtocolResponse.lambda$getResponseFunction$2(JsonWireProtocolResponse.java:91)
	at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$0(ProtocolHandshake.java:122)
	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
	at java.util.Spliterators$ArraySpliterator.tryAdvance(Unknown Source)
	at java.util.stream.ReferencePipeline.forEachWithCancel(Unknown Source)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(Unknown Source)
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.util.stream.FindOps$FindOp.evaluateSequential(Unknown Source)
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.util.stream.ReferencePipeline.findFirst(Unknown Source)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:125)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:73)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:136)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:548)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:212)
	at org.openqa.selenium.ie.InternetExplorerDriver.run(InternetExplorerDriver.java:221)
	at org.openqa.selenium.ie.InternetExplorerDriver.<init>(InternetExplorerDriver.java:213)
	at org.openqa.selenium.ie.InternetExplorerDriver.<init>(InternetExplorerDriver.java:150)
	at NaveenPackage_New.InternetExplorerWebDriverBasic.main(InternetExplorerWebDriverBasic.java:20)

**Comment by rfmirza123** [comment]
I was able to run IE browser by changing a minor thing:
public static void main(String[] args) throws InterruptedException {System.setProperty("webdriver.ie.driver","C:\\Users\\rfmir\\OneDrive\\Desktop\\selenium12\\IEDriverServer.exe");
			WebDriver driver = new InternetExplorerDriver();
Simply changing above from to: driver = New InternetExploreDriver
and setting Browser zoom to 100%.

Thank you.
